In [9]:
import pandas as pd
import os
import tkinter as tk
from tkinter import filedialog

# 1. 弹窗选择文件
print("⏳ 请在弹出的窗口中选择你的 CSV 账单文件...")

# 创建一个隐藏的根窗口（防止弹出一个空的 tk 界面）
root = tk.Tk()
root.withdraw()
root.wm_attributes('-topmost', 1) # 让弹窗置顶，不然容易被 VS Code 挡住

# 打开文件选择对话框
file_path = filedialog.askopenfilename(
    title="请选择 Moze 账单文件",
    filetypes=[("CSV Files", "*.csv"), ("All Files", "*.*")]
)

# 2. 判断你有没有选文件
if not file_path:
    print("❌ 你取消了选择，没有读取任何文件。")
else:
    print(f"✅ 你选择了文件:\n{file_path}")
    
    # 3. 读取文件逻辑（自动处理编码）
    try:
        df = pd.read_csv(file_path, encoding='utf-8')
    except UnicodeDecodeError:
        print("⚠️ UTF-8 解码失败，自动切换为 GBK 编码...")
        df = pd.read_csv(file_path, encoding='gbk')
    except Exception as e:
        print(f"❌ 读取出错: {e}")
        df = None

    # 4. 展示数据
    if df is not None:
        print(f"\n🎉 成功读取！表格共有 {len(df)} 行。")
        display(df.head()) # 显示前5行

⏳ 请在弹出的窗口中选择你的 CSV 账单文件...
✅ 你选择了文件:
F:/TZY_YX/工作/2025/Moze4.0/Moze4.0_Import/MOZE导入_20260128_171350.csv

🎉 成功读取！表格共有 1681 行。

,账户,币种,记录类型,主类别,子类别,金额,手续费,折扣,名称,商家,日期,时间,项目,描述,标签,对象
0,平安银行4946,CNY,支出,饮食,饮料水果,-13.90,0,0,水果,超马鲜生,2025/12/29,18:15:00,食,苹果,#AliPay,NaN
1,平安银行4946,CNY,支出,饮食,食材,-24.70,0,0,熟食,超马鲜生,2025/12/29,17:57:00,食,.北京烤鸭,#AliPay,NaN
2,平安银行4946,CNY,支出,购物,日常用品,-49.50,0,0,NaN,拼多多,2025/12/29,12:21:00,日用&家用,.机油0.9L,#AliPay,NaN
3,平安银行4946,CNY,支出,饮食,食材,-2.32,0,0,蔬菜,超马鲜生,2025/12/28,19:54:00,食,白菜,#AliPay,NaN
4,平安银行4946,CNY,支出,饮食,食材,-29.90,0,0,NaN,超马鲜生,2025/12/28,19:54:00,食,.麦片,#AliPay,NaN

In [10]:
# 看看数据的列名和基本信息
# 这能帮我们决定下一步该清洗哪一列
print("=== 数据的列名 ===")
print(df.columns)

print("\n=== 数据预览 ===")
display(df.head(10)) # 看看前10行

=== 数据的列名 ===
Index(['账户', '币种', '记录类型', '主类别', '子类别', '金额', '手续费', '折扣', '名称', '商家', '日期',
       '时间', '项目', '描述', '标签', '对象'],
      dtype='object')

=== 数据预览 ===

,账户,币种,记录类型,主类别,子类别,金额,手续费,折扣,名称,商家,日期,时间,项目,描述,标签,对象
0,平安银行4946,CNY,支出,饮食,饮料水果,-13.90,0,0,水果,超马鲜生,2025/12/29,18:15:00,食,苹果,#AliPay,NaN
1,平安银行4946,CNY,支出,饮食,食材,-24.70,0,0,熟食,超马鲜生,2025/12/29,17:57:00,食,.北京烤鸭,#AliPay,NaN
2,平安银行4946,CNY,支出,购物,日常用品,-49.50,0,0,NaN,拼多多,2025/12/29,12:21:00,日用&家用,.机油0.9L,#AliPay,NaN
3,平安银行4946,CNY,支出,饮食,食材,-2.32,0,0,蔬菜,超马鲜生,2025/12/28,19:54:00,食,白菜,#AliPay,NaN
4,平安银行4946,CNY,支出,饮食,食材,-29.90,0,0,NaN,超马鲜生,2025/12/28,19:54:00,食,.麦片,#AliPay,NaN
5,平安银行4946,CNY,支出,饮食,饮料水果,-5.00,0,0,水果,超马鲜生,2025/12/28,19:54:00,食,哈密瓜,#AliPay,NaN
6,平安银行4946,CNY,支出,购物,日常用品,-10.80,0,0,NaN,拼多多,2025/12/27,15:10:00,日用&家用,.牌照框,#AliPay,NaN
7,平安银行4946,CNY,支出,饮食,食材,-13.80,0,0,蛋及蛋制品,超马鲜生,2025/12/27,13:28:00,食,鸡蛋,#AliPay,NaN
8,平安银行4946,CNY,支出,饮食,食材,-2.76,0,0,NaN,超马鲜生,2025/12/27,13:28:00,食,鲜面条,#AliPay,NaN
9,平安银行4946,CNY,支出,饮食,食材,-15.21,0,0,NaN,超马鲜生,2025/12/27,13:25:00,食,生水饺,#AliPay,NaN

In [11]:
import pandas as pd
import tkinter as tk
from tkinter import filedialog

# 1. 弹窗选文件
print("⏳ 请在弹出的窗口选文件...")
root = tk.Tk()
root.withdraw()
root.wm_attributes('-topmost', 1) # 窗口置顶

file_path = filedialog.askopenfilename(title="选择账单CSV")

# 2. 读取并存入变量 df
if file_path:
    try:
        df = pd.read_csv(file_path, encoding='utf-8')
    except:
        df = pd.read_csv(file_path, encoding='gbk')
    print(f"✅ 成功！数据已保存在变量 'df' 中，共 {len(df)} 行。")
else:
    print("❌ 未选择文件")

⏳ 请在弹出的窗口选文件...
✅ 成功！数据已保存在变量 'df' 中，共 1681 行。

In [12]:
# 这里可以直接用 df，因为第1格已经把它准备好了

# 1. 查看前5行，看看长什么样
display(df.head())

# 2. 看看都有哪些列（比如：交易时间、金额、备注...）
print("列名列表:", df.columns.tolist())

# 3. 统计一下有多少行
print("总行数:", len(df))

# 4. (假设你有一列叫'金额') 简单算个总和试试
# print("总金额:", df['金额'].sum())

,账户,币种,记录类型,主类别,子类别,金额,手续费,折扣,名称,商家,日期,时间,项目,描述,标签,对象
0,平安银行4946,CNY,支出,饮食,饮料水果,-13.90,0,0,水果,超马鲜生,2025/12/29,18:15:00,食,苹果,#AliPay,NaN
1,平安银行4946,CNY,支出,饮食,食材,-24.70,0,0,熟食,超马鲜生,2025/12/29,17:57:00,食,.北京烤鸭,#AliPay,NaN
2,平安银行4946,CNY,支出,购物,日常用品,-49.50,0,0,NaN,拼多多,2025/12/29,12:21:00,日用&家用,.机油0.9L,#AliPay,NaN
3,平安银行4946,CNY,支出,饮食,食材,-2.32,0,0,蔬菜,超马鲜生,2025/12/28,19:54:00,食,白菜,#AliPay,NaN
4,平安银行4946,CNY,支出,饮食,食材,-29.90,0,0,NaN,超马鲜生,2025/12/28,19:54:00,食,.麦片,#AliPay,NaN

列名列表: ['账户', '币种', '记录类型', '主类别', '子类别', '金额', '手续费', '折扣', '名称', '商家', '日期', '时间', '项目', '描述', '标签', '对象']
总行数: 1681

In [13]:
# 把所有的 NaN 替换成 空字符串 (也就是什么都不显示)
df = df.fillna('')

# 或者把 NaN 替换成 "无"
# df = df.fillna('无')

# 再次查看，清爽多了
display(df.head())

,账户,币种,记录类型,主类别,子类别,金额,手续费,折扣,名称,商家,日期,时间,项目,描述,标签,对象
0,平安银行4946,CNY,支出,饮食,饮料水果,-13.90,0,0,水果,超马鲜生,2025/12/29,18:15:00,食,苹果,#AliPay,
1,平安银行4946,CNY,支出,饮食,食材,-24.70,0,0,熟食,超马鲜生,2025/12/29,17:57:00,食,.北京烤鸭,#AliPay,
2,平安银行4946,CNY,支出,购物,日常用品,-49.50,0,0,,拼多多,2025/12/29,12:21:00,日用&家用,.机油0.9L,#AliPay,
3,平安银行4946,CNY,支出,饮食,食材,-2.32,0,0,蔬菜,超马鲜生,2025/12/28,19:54:00,食,白菜,#AliPay,
4,平安银行4946,CNY,支出,饮食,食材,-29.90,0,0,,超马鲜生,2025/12/28,19:54:00,食,.麦片,#AliPay,

In [14]:
import pandas as pd

# 1. 造一点“脏”数据
# 注意看：里面故意加了空格、中文括号（）、英文括号()
dirty_columns = [' 姓名 ', '年龄（岁）', '邮箱(Email)', '备注 ']
df_test = pd.DataFrame(columns=dirty_columns)

print("🔴 清洗前（原样）：")
print(df_test.columns.tolist())

# 2. 运行你的清洗代码
# 你的逻辑：转字符串 -> 去空格 -> 把 '（' 和 '(' 统一变成 '(' -> 把 '）' 和 ')' 统一变成 ')'
df_test.columns = df_test.columns.astype(str).str.strip() \
    .str.replace('[（(]', '(', regex=True) \
    .str.replace('[）)]', ')', regex=True)

# 3. 查看结果
print("\n🟢 清洗后（预期应该没空格，且全是英文括号）：")
print(df_test.columns.tolist())

# 4. 自动检查逻辑（给你吃个定心丸）
expected_columns = ['姓名', '年龄(岁)', '邮箱(Email)', '备注']
if df_test.columns.tolist() == expected_columns:
    print("\n✅ 测试通过！代码逻辑完美。")
else:
    print("\n❌ 测试失败，结果和预期不符。")

🔴 清洗前（原样）：
[' 姓名 ', '年龄（岁）', '邮箱(Email)', '备注 ']

🟢 清洗后（预期应该没空格，且全是英文括号）：
['姓名', '年龄(岁)', '邮箱(Email)', '备注']

✅ 测试通过！代码逻辑完美。

---
## 调试 sniff_and_load_data 函数

下面是从主脚本中提取的 `sniff_and_load_data` 函数，用于调试和测试。

In [ ]:
# 导入必要的库
import pandas as pd
from pathlib import Path

# 列名映射字典（从主脚本复制）
COLUMN_MAPPING = {
    '交易时间': '交易时间', '交易创建时间': '交易时间', '付款时间': '交易时间',
    '交易类型': '交易类型', '交易分类': '交易类型', '交易对方': '交易对方',
    '商品': '商品', '商品名称': '商品', '收/支': '收/支',
    '金额(元)': '金额(元)', '金额（元）': '金额(元)', '金额': '金额(元)',
    '支付方式': '支付方式', '收/付款方式': '支付方式',
    '当前状态': '当前状态', '交易状态': '当前状态',
    '备注': '备注', '交易单号': '交易单号', '交易订单号': '交易单号',
    '商户单号': '商户单号', '商家订单号': '商户单号', '商品说明': '商品'
}

print("✅ 导入完成，COLUMN_MAPPING 已加载")

In [ ]:
def sniff_and_load_data(file_path: Path):
    """
    读取支付宝/微信账单文件
    
    参数:
        file_path: 账单文件路径 (Path 对象)
    
    返回:
        DataFrame 或 None
    """
    print(f"📁 读取文件: {file_path.name}")
    print(f"   后缀: {file_path.suffix.lower()}")
    
    ftype, df = None, None
    
    try:
        # === 步骤1: 根据文件类型读取 ===
        if file_path.suffix.lower() == '.csv':
            print("   类型: CSV → 支付宝账单")
            print("   参数: header=24, encoding=gb18030")
            df = pd.read_csv(file_path, header=24, encoding='gb18030')
            ftype = "AliPay"
        elif file_path.suffix.lower() == '.xlsx':
            print("   类型: XLSX → 微信账单")
            print("   参数: header=16, engine=openpyxl")
            df = pd.read_excel(file_path, header=16, engine='openpyxl')
            ftype = "WeChat"
        else:
            print(f"   ❌ 不支持的文件类型: {file_path.suffix}")
            return None
            
        if df is None:
            print("   ❌ DataFrame 为空")
            return None
        
        print(f"   ✅ 读取成功: {len(df)} 行 × {len(df.columns)} 列")
        
        # === 步骤2: 清理列名 ===
        print(f"\n🔧 原始列名: {list(df.columns)[:5]}...")  # 只显示前5个
        
        df.columns = df.columns.astype(str).str.strip().str.replace(
            '[（(]', '(', regex=True).str.replace('[）)]', ')', regex=True)
        
        print(f"   清理后: {list(df.columns)[:5]}...")
        
        # === 步骤3: 列名映射 ===
        df.rename(columns=COLUMN_MAPPING, inplace=True)
        print(f"   映射后: {list(df.columns)[:5]}...")
        
        # === 步骤4: 检查必需列 ===
        if '金额(元)' not in df.columns:
            print(f"   ❌ 缺少 '金额(元)' 列")
            print(f"   当前列: {list(df.columns)}")
            return None
        
        # === 步骤5: 处理金额列 ===
        print(f"\n💰 金额列处理:")
        print(f"   原始类型: {df['金额(元)'].dtype}")
        print(f"   示例值: {df['金额(元)'].head(3).tolist()}")
        
        df['金额(元)'] = pd.to_numeric(
            df['金额(元)'].astype(str).str.replace(r'[¥,]', '', regex=True).str.strip(),
            errors='coerce'
        ).fillna(0)
        
        df['金额'] = df['金额(元)']
        
        print(f"   处理后类型: {df['金额(元)'].dtype}")
        print(f"   处理后示例: {df['金额(元)'].head(3).tolist()}")
        
        # === 步骤6: 添加标签 ===
        df['_source_tag'] = '#WechatPay' if ftype == "WeChat" else '#AliPay'
        
        print(f"\n✅ 处理完成 (类型: {ftype})")
        print(f"   总行数: {len(df)}")
        print(f"   总金额: {df['金额'].sum():.2f} 元")
        
        return df
        
    except Exception as e:
        print(f"\n❌ 读取失败: {e}")
        import traceback
        traceback.print_exc()
        return None

print("✅ 函数 sniff_and_load_data 已定义")

### 方法1: 使用文件选择对话框测试